# Disposable Windows 11 VM coexistence stress test.
# Requires signed/installed AntiOS native components, active Microsoft Defender,
# and the harmless clean executable generated by native/tests/inert_program.c.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ServiceExecutable,
    [Parameter(Mandatory)][string]$CleanFixture,
    [Parameter(Mandatory)][string]$ReportPath,
    [ValidateRange(8,64)][int]$ParallelOpens = 24
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$service = (Resolve-Path -LiteralPath $ServiceExecutable).Path
$fixture = (Resolve-Path -LiteralPath $CleanFixture).Path
$report = [ordered]@{
    utc = [DateTime]::UtcNow.ToString('o')
    parallelOpens = $ParallelOpens
    passed = $false
}

function Driver-Status {
    $raw = & $service --driver-status
    if ($LASTEXITCODE -ne 0) { throw 'AntiOS driver status unavailable.' }
    return $raw | ConvertFrom-Json
}

Add-Type @'
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;

public sealed class AntiOSOpenResult {
    public string Path;
    public bool Opened;
    public int Error;
    public long Milliseconds;
}

public static class AntiOSCoexistenceIo {
    const uint FILE_EXECUTE = 0x20;
    const uint SHARE_ALL = 0x00000001 | 0x00000002 | 0x00000004;
    const uint OPEN_EXISTING = 3;

    [DllImport("kernel32.dll", CharSet=CharSet.Unicode, SetLastError=true)]
    static extern IntPtr CreateFile(
        string path, uint access, uint share, IntPtr security,
        uint disposition, uint flags, IntPtr template);

    [DllImport("kernel32.dll", SetLastError=true)]
    static extern bool CloseHandle(IntPtr handle);

    public static AntiOSOpenResult[] ExecuteOpenMany(string[] paths) {
        var gate = new ManualResetEventSlim(false);
        var tasks = new Task<AntiOSOpenResult>[paths.Length];
        for (int i = 0; i < paths.Length; ++i) {
            string path = paths[i];
            tasks[i] = Task.Run(() => {
                gate.Wait();
                var timer = Stopwatch.StartNew();
                IntPtr handle = CreateFile(path, FILE_EXECUTE, SHARE_ALL, IntPtr.Zero,
                                           OPEN_EXISTING, 0, IntPtr.Zero);
                int error = Marshal.GetLastWin32Error();
                bool opened = handle != new IntPtr(-1);
                if (opened) CloseHandle(handle);
                timer.Stop();
                return new AntiOSOpenResult {
                    Path = path, Opened = opened,
                    Error = opened ? 0 : error,
                    Milliseconds = timer.ElapsedMilliseconds
                };
            });
        }
        gate.Set();
        Task.WaitAll(tasks);
        var results = new AntiOSOpenResult[tasks.Length];
        for (int i = 0; i < tasks.Length; ++i) results[i] = tasks[i].Result;
        gate.Dispose();
        return results;
    }
}
'@

$temp = Join-Path ([IO.Path]::GetTempPath()) ('AntiOS-Coexistence-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temp | Out-Null
try {
    $mp = Get-MpComputerStatus
    $report.defender = [ordered]@{
        runningMode = [string]$mp.AMRunningMode
        antivirusEnabled = [bool]$mp.AntivirusEnabled
        realTimeProtectionEnabled = [bool]$mp.RealTimeProtectionEnabled
        behaviorMonitorEnabled = [bool]$mp.BehaviorMonitorEnabled
        ioavProtectionEnabled = [bool]$mp.IoavProtectionEnabled
        tamperProtected = [bool]$mp.IsTamperProtected
        signatureVersion = [string]$mp.AntivirusSignatureVersion
    }
    if (-not $mp.AntivirusEnabled -or -not $mp.RealTimeProtectionEnabled) {
        throw 'Microsoft Defender real-time protection must remain active for this coexistence test.'
    }

    $filterList = (& "$env:SystemRoot\System32\fltmc.exe" filters 2>&1 | Out-String)
    $report.wdFilterLoaded = [bool]($filterList -match '(?im)^\s*WdFilter\s+')
    $report.antiOSFilterLoaded = [bool]($filterList -match '(?im)^\s*AntiOS-Filter\s+')
    if (-not $report.wdFilterLoaded) { throw 'WdFilter is not loaded; Defender filesystem coexistence is not being exercised.' }
    if (-not $report.antiOSFilterLoaded) { throw 'AntiOS-Filter is not loaded.' }

    $before = Driver-Status
    $report.driverBefore = $before
    if ([int]$before.protocol -lt 2) { throw 'Native protocol v2+ is required.' }
    if ([int]$before.coexistence_mode -ne 1) { throw 'Driver CoexistenceMode must be enabled.' }
    if ([int]$before.max_pending -lt 1 -or [int]$before.max_pending -gt 4) {
        throw 'Driver MaxPendingScans exceeds the four-worker native broker capacity.'
    }
    if ([int]$before.pending -ne 0) { throw 'Driver had pending scans before the stress test.' }

    $paths = @()
    for ($i = 0; $i -lt $ParallelOpens; ++$i) {
        $path = Join-Path $temp ("clean-{0:D2}.exe" -f $i)
        Copy-Item -LiteralPath $fixture -Destination $path
        $paths += $path
    }

    # Give Defender a moment to observe the newly written harmless executables.
    Start-Sleep -Milliseconds 250
    $results = [AntiOSCoexistenceIo]::ExecuteOpenMany([string[]]$paths)
    $report.opens = @($results | ForEach-Object {
        [ordered]@{ path = $_.Path; opened = $_.Opened; error = $_.Error; milliseconds = $_.Milliseconds }
    })

    $failed = @($results | Where-Object { -not $_.Opened })
    if ($failed.Count) {
        throw "Clean execute-open failed under parallel Defender coexistence: $($failed[0].Error)"
    }
    $maxOpenMs = ($results | Measure-Object -Property Milliseconds -Maximum).Maximum
    $report.maxOpenMilliseconds = [long]$maxOpenMs
    if ([long]$maxOpenMs -gt 15000) { throw 'Parallel execute-open exceeded the coexistence latency ceiling.' }

    Start-Sleep -Milliseconds 250
    $after = Driver-Status
    $report.driverAfter = $after

    $attemptDelta = [long]$after.attempts - [long]$before.attempts
    $blockDelta = [long]$after.blocked - [long]$before.blocked
    $busyDelta = [long]$after.busy_bypass - [long]$before.busy_bypass
    $sectionConflictDelta = [long]$after.section_conflicts - [long]$before.section_conflicts
    $deliveryTimeoutDelta = [long]$after.delivery_timeouts - [long]$before.delivery_timeouts
    $completionTimeoutDelta = [long]$after.completion_timeouts - [long]$before.completion_timeouts
    $report.delta = [ordered]@{
        attempts = $attemptDelta
        blocked = $blockDelta
        busyBypass = $busyDelta
        sectionConflicts = $sectionConflictDelta
        deliveryTimeouts = $deliveryTimeoutDelta
        completionTimeouts = $completionTimeoutDelta
    }

    if ([int]$after.pending -ne 0) { throw 'Native scan queue did not drain.' }
    if ([int]$after.peak_pending -gt [int]$after.max_pending) { throw 'Observed pending scans exceeded the configured bound.' }
    if ($attemptDelta -lt $ParallelOpens) { throw 'Not every distinct execute-open reached native scan admission.' }
    if ($blockDelta -ne 0) { throw 'Clean coexistence fixtures were unexpectedly blocked.' }
    if ([long]$after.max_wait_ms -gt 15000) { throw 'Driver-observed wait exceeded the coexistence latency ceiling.' }

    $mpAfter = Get-MpComputerStatus
    $report.defenderAfter = [ordered]@{
        runningMode = [string]$mpAfter.AMRunningMode
        antivirusEnabled = [bool]$mpAfter.AntivirusEnabled
        realTimeProtectionEnabled = [bool]$mpAfter.RealTimeProtectionEnabled
        behaviorMonitorEnabled = [bool]$mpAfter.BehaviorMonitorEnabled
        ioavProtectionEnabled = [bool]$mpAfter.IoavProtectionEnabled
        tamperProtected = [bool]$mpAfter.IsTamperProtected
        signatureVersion = [string]$mpAfter.AntivirusSignatureVersion
    }
    if (-not $mpAfter.AntivirusEnabled -or -not $mpAfter.RealTimeProtectionEnabled) {
        throw 'Microsoft Defender real-time protection was no longer active after the coexistence stress run.'
    }

    $report.passed = $true
} catch {
    $report.error = $_.Exception.Message
    throw
} finally {
    if (Test-Path -LiteralPath $temp) {
        Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue
    }
    $report | ConvertTo-Json -Depth 8 | Set-Content -Encoding utf8 -LiteralPath $ReportPath
}
